import argparse
import pandas as pd
from pathlib import Path
import yaml
import shutil


def transfer_dlc_labels(folders: list[str], target_config_path: str):
    """
    Transfers DLC labels from a source project to a newly created target project.

    This utility solves the problem of "bootstrapping" a new, specialized network
    using predictions generated by a general, pre-trained network.

    Workflow:
      1. Reads the target `config.yaml` to extract expected bodyparts and scorer name.
      2. Iterates over the provided source folders.
      3. For each folder, finds the `CollectedData_[scorer].csv`.
      4. Strips out any bodyparts not present in the target config.
      5. Renames the scorer in the DataFrame to match the target config.
      6. Creates a new subfolder (`transferred_to_[new_scorer]`).
      7. Saves the modified `.csv` and `.h5` files into the new subfolder.
      8. Copies all image frames to the new subfolder.

    The resulting subfolder is 100% self-contained and ready to be dropped
    directly into the `labeled-data` directory of your target DLC project.
    """
    config_file = Path(target_config_path)

    if not config_file.exists():
        print(f"Error: Config file not found -> {config_file}")
        return

    # 1. Read Target Config
    with open(config_file, "r") as f:
        target_config = yaml.safe_load(f)

    target_bodyparts = target_config.get("bodyparts", [])
    target_scorer = target_config.get("scorer", "unknown_scorer")

    if not target_bodyparts:
        print("Error: Target config.yaml has no bodyparts defined.")
        return

    print(f"Target Scorer: {target_scorer}")
    print(f"Target Bodyparts: {target_bodyparts}\n")

    for folder_str in folders:
        print("-" * 50)
        folder_path = Path(folder_str)
        if not folder_path.exists() or not folder_path.is_dir():
            print(f"Error: Directory does not exist or is invalid -> {folder_path}")
            continue

        print(f"Processing folder: {folder_path.name}")

        # Validate CSV
        csv_files = list(folder_path.glob("CollectedData_*.csv"))
        if not csv_files:
            print(f"  Error: No CollectedData_*.csv found in {folder_path.name}. Skipping.")
            continue

        csv_file = csv_files[0]

        # Validate H5
        h5_file = csv_file.with_suffix(".h5")
        if not h5_file.exists():
            print(f"  Error: Found CSV but missing corresponding H5 -> {h5_file.name}. Skipping.")
            continue

        # Validate Frames
        frame_extensions = [".png", ".jpg", ".jpeg"]
        frames = [f for f in folder_path.iterdir() if f.is_file() and f.suffix.lower() in frame_extensions]
        if not frames:
            print("  Warning: No image frames found! The output folder will only contain data files.")

        try:
            df = pd.read_csv(csv_file, header=[0, 1, 2], index_col=[0, 1, 2])
        except Exception as e:
            print(f"  Error reading CSV: {e}")
            continue

        # 3. Slice to keep only target bodyparts
        idx = pd.IndexSlice
        source_bodyparts = df.columns.get_level_values(1).unique()

        missing = [bp for bp in target_bodyparts if bp not in source_bodyparts]
        if missing:
            print(f"  Warning: Target bodyparts missing from source -> {missing}")

        valid_targets = [bp for bp in target_bodyparts if bp in source_bodyparts]
        if not valid_targets:
            print("  Error: None of the target bodyparts exist in this CSV. Skipping.")
            continue

        df_stripped = df.loc[:, idx[:, valid_targets, :]]

        # 4. Rename Scorer
        df_stripped.columns = df_stripped.columns.set_levels([target_scorer], level=0)

        # 5. Create output directory
        out_dir = folder_path / f"transferred_to_{target_scorer}"
        out_dir.mkdir(exist_ok=True)

        out_csv = out_dir / f"CollectedData_{target_scorer}.csv"
        out_h5 = out_dir / f"CollectedData_{target_scorer}.h5"

        df_stripped.to_csv(out_csv)
        df_stripped.to_hdf(out_h5, key="df_with_missing", mode="w", format="fixed")

        # 6. Copy frames so the folder is fully self-contained for DLC
        frames_copied = 0
        if frames:
            for item in frames:
                shutil.copy2(item, out_dir / item.name)
                frames_copied += 1

        print(f"  -> Saved CSV and H5 to {out_dir.name}")
        if frames_copied > 0:
            print(f"  -> Copied {frames_copied} frames.")
        print("")


if __name__ == "__main__":
    description = (
        "Transfer DLC labels from one project to another by stripping unused bodyparts.\n\n"
        "This utility is designed for cross-network bootstrapping. It takes folders labeled by a\n"
        "source network, prunes the data to match a target network's config.yaml, and packages\n"
        "them into self-contained directories ready to be copied to the target project."
    )

    parser = argparse.ArgumentParser(
        description=description,
        formatter_class=argparse.RawTextHelpFormatter
    )

    parser.add_argument(
        "config_path",
        help="Path to the TARGET project's config.yaml file.\n"
             "The script will read this file to determine which bodyparts to keep\n"
             "and what the new scorer name should be."
    )

    parser.add_argument(
        "folders",
        nargs="+",
        help="One or more directory paths. Each directory MUST contain:\n"
             "  - A CollectedData_*.csv file\n"
             "  - The corresponding .h5 file\n"
             "  - The .png/.jpg frame images"
    )

    args = parser.parse_args()
    transfer_dlc_labels(args.folders, args.config_path)
